# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-on-texlive-latest:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install fonts
        run: |
            mkdir -p ~/.fonts
            mv settings_files/FontFiles/simhei.ttf ~/.fonts
            mv settings_files/FontFiles/simsun.ttc ~/.fonts
            mv settings_files/FontFiles/Times-New-Roman.ttf ~/.fonts
            fc-cache -vf
      - name: Build PDF
        run: |
            latexmk -synctex=1 -file-line-error -interaction=nonstopmode -xelatex scutthesis
  build-on-texlive-2021:
    runs-on: ubuntu-latest
    container: texlive/texlive:TL2021-historic
    steps:
      - uses: actions/checkout@v3
      - name: Install fonts
        run: |
            mkdir -p ~/.fonts
            mv settings_files/FontFiles/simhei.ttf ~/.fonts
            mv settings_files/FontFiles/simsun.ttc ~/.fonts
            mv settings_files/FontFiles/Times-New-Roman.ttf ~/.fonts
            fc-cache -vf
      - name: Build PDF
        run: |
            latexmk -synctex=1 -file-line-error -interaction=nonstopmode -xelatex scutthesis
  build-on-texlive-2020:
    runs-on: ubuntu-latest
    container: texlive/texlive:TL2020-historic
    steps:
      - uses: actions/checkout@v3
      - name: Install fonts
        run: |
            mkdir -p ~/.fonts
            mv settings_files/FontFiles/simhei.ttf ~/.fonts
            mv settings_files/FontFiles/simsun.ttc ~/.fonts
            mv settings_files/FontFiles/Times-New-Roman.ttf ~/.fonts
            fc-cache -vf
      - name: Build PDF
        run: |
            latexmk -synctex=1 -file-line-error -interaction=nonstopmode -xelatex scutthesis
  build-on-texlive-2019:
    runs-on: ubuntu-latest
    container: texlive/texlive:TL2019-historic
    steps:
      - uses: actions/checkout@v3
      - name: Install fonts
        run: |
            mkdir -p ~/.fonts
            mv settings_files/FontFiles/simhei.ttf ~/.fonts
            mv settings_files/FontFiles/simsun.ttc ~/.fonts
            mv settings_files/FontFiles/Times-New-Roman.ttf ~/.fonts
            fc-cache -vf
      - name: Build PDF
        run: |
            latexmk -synctex=1 -file-line-error -interaction=nonstopmode -xelatex scutthesis
